= Case #003: The Miami Marina Murder

== Setup
A body was found floating near the docks of Coral Bay Marina in the early hours of August 14, 1986.
Your job, detective, is to find the murderer and bring them to justice.
This case might require the use of JOINs, wildcard searches, and logical deduction.
Get to work, detective.

== Objectives
Find the murderer.

== Retrieve the crime scene report

=== Query

[source, sql]
----
SELECT *
FROM crime_scene
WHERE location IS 'Coral Bay Marina'
AND date IS '19860814'
----

=== Result
|===
|id	|date	|location	|description

|43
|19860814
|Coral Bay Marina
|The body of an unidentified man was found near the docks.
Two people were seen nearby: one who lives on 300ish "Ocean Drive" and another whose first name ends with "ul" and his last name ends with "ez".
|===


== Find suspects/witnesses

=== Query

[source, sql]
----
SELECT *
FROM person
WHERE address LIKE '3__ Ocean Drive'
OR name LIKE '%ul %ez'
LIMIT 10
----

=== Result
|===
|id	    |name	        |alias	    |occupation	        |address

|101	|Carlos Mendez	|Los Ojos	|Fisherman	        |369 Ocean Drive
|102	|Raul Gutierrez	|The Cobra	|Nightclub Owner	|45 Sunset Ave
|===


== Retrieve suspects/witnesses' interview transcripts

=== Query

[source, sql]
----
SELECT p.id, p.name, i.transcript
FROM person AS p
JOIN interviews AS i
ON p.id = i.person_id
WHERE person_id IN (101, 102)
----

=== Result
|===
|id	    |name	        |transcript

|101	|Carlos Mendez	|I saw someone check into a hotel on August 13. The guy looked nervous.
|102	|Raul Gutierrez	|I heard someone checked into a hotel with "Sunset" in the name.
|===


== Find hotel check-in details

=== Query
[source, sql]
----
SELECT *
FROM surveillance_records
WHERE suspicious_activity is not NULL
AND person_id IN (
  SELECT hc.person_id
  FROM hotel_checkins AS hc
  WHERE hc.hotel_name LIKE '%Sunset%'
  AND hc.check_in_date = 19860813
)
----

=== Result

Lots of results, but three real suspicious activities:

|===
|id	|person_id	|hotel_checkin_id	|suspicious_activity

|6	|6	        |34	                |Spotted entering late at night
|7	|7	        |89	                |Seen arguing with an unknown person
|8	|8	        |2	                |Left suddenly at 3 AM
|===


== Find murderer

=== Query
[source, sql]
----
SELECT p.name, c.confession
FROM person AS p
JOIN confessions AS c
ON p.id = c.person_id
WHERE p.id in (6, 7, 8)
----

=== Result

|===
|name	        |confession

|James Wilson	|I don't know anything about this.
|Robert Smith	|I was just walking my dog that night.
|Thomas Brown	|Alright! I did it. I was paid to make sure he never left the marina alive.
|===

== Conclusion
The murderer is Thomas Brown.